import random

def init_questions(schema, num_questions, text_to_sql):
    questions = [
    "Qiojwfiamadoaijf",
    "Qijfoiaj fajoiqh qn adnihwf jahdoiadjaijd qwbrb",
    "!!!!!dkamofao$#$$$dfoajfoakkfalmas",
    "Show the names in the database",
    "List all columns and their data types for a table",
    "Identify foreign keys and their referenced tables",
    "Identify tables with a date or timestamp column",
    "When data stored",
    "AAAAAAAAAAAAAAAAAAAA",
    "a4$$455kjaofm aas gfwww are",
    "jks hafsfd fjskhfnjs fnsjnsj fnsjknfdkj nfjksn sjnfksjn fsddd nfjsknfkj fsnsss them",
    "??????????????????",
    "Describe the relationships between tables",
    "Identify columns with auto-increment properties",
    "List columns with enumerated types and their possible values",
    "Retrieve the minimum and maximum values for columns of numeric data",
    "Display the character set for text columns",
    "Identify tables that contain geospatial data types",
    "Show the data type and length for all columns",
    "Display tables that have binary or boolean columns",
    "Identify all tables with a timestamp",
    "Display all user-defined types and their underlying structure",
    "How data is structured in column",
    "What data values database contain",
    "Where data belong to and is associated with and does contain and dakd dajijsid dalks jds sds adjisj disd sij dijs dijs sjaijkajad sjida dkajd ajd",
    "Who data",
    "More?",
    "#@@@#$%^&%",
    "How much money?",
    "What are distinct types",
    "Xkzmv9#@!klsd",
    "List all indexes in the database",
    "Show primary keys for each table",
    "Identify unique constraints in tables",
    "Describe the schema version history",
    "Find tables with large text fields",
    "List all triggers and their associated tables",
    "Show stored procedures in the database",
    "Identify views and their underlying tables",
    "List all sequences and their current values",
    "Show user roles and permissions",
    "Identify nullable columns in tables",
    "List all check constraints in the database",
    "Show default values for columns",
    "Identify partitioned tables",
    "List all materialized views",
    "Show all user-defined functions",
    "Identify recursive relationships in tables",
    "List all synonyms in the database",
    "Show all constraints for a specific table",
    "Identify columns with foreign key references",
    "List all databases on the server",
    "Show the owner of each table",
    "Identify tables without primary keys",
    "List all column comments",
    "Show table creation dates",
    "Identify tables with composite primary keys",
    "List all temporary tables",
    "Show the size of each table",
    "Identify tables with binary large objects",
    "List all character varying columns",
    "Show ENUM type definitions",
    "Identify tables with JSON columns",
    "List all columns with default expressions",
    "Show inherited tables",
    "Identify columns with unique indexes",
    "List all columns that are part of a composite index",
    "Show the collation settings for text columns",
    "Identify tables with hierarchical data",
    "List all columns with spatial indexes",
    "Show the storage engine for each table",
    "Identify tables with full-text search indexes",
    "List all columns with auto-generated values",
    "Show the replication settings for the database",
    "Identify tables with partitioning schemes",
    "List all columns using the DECIMAL data type",
    "Show the last modification time for each table",
    "Identify tables with temporal tables",
    "List all columns with the BOOLEAN data type",
    "Show the encryption settings for sensitive columns",
    "Identify tables with audit trails",
    "List all columns with constraints",
    "Show the relationships between foreign keys and primary keys",
    "Identify tables with versioning",
    "List all columns that use the UUID data type",
    "Show the default schema for the database",
    "Identify tables with cascading deletes",
    "List all columns with unique constraints",
    "Show the indexing strategy for large tables",
    "Identify tables with self-referencing foreign keys",
    "List all columns with temporal data types",
    "Show the character length limits for string columns",
    "Identify tables with external data sources",
    "List all columns with precision and scale",
    "Show the normalization level of the database",
    "Identify tables with soft deletes",
    "List all columns with binary data types",
    "Show the default values for enumerated columns",
    "Identify tables with multiple foreign keys",
    "List all columns with indexed values",
    "Show the data distribution statistics for columns",
    "Identify tables with read-only access",
    "List all columns with non-null constraints",
    "Show the inheritance hierarchy of tables",
    "Identify tables with multi-language support",
    "List all columns with unique indexes",
    "Show the foreign key constraints for a specific table",
    "Identify tables with composite foreign keys",
    "List all columns that are foreign keys",
    "Show the referential actions for foreign keys",
    "Identify tables with temporal constraints",
    "List all columns with computed values",
    "Show the data lineage for specific columns",
    "Identify tables with hierarchical structures",
    "List all columns with default sequences",
    "Show the backup schedules for the database",
    "Identify tables with user-defined data types",
    "List all columns with encryption",
    "Show the data retention policies for tables",
    "Identify tables with data sharding",
    "List all columns with indexed foreign keys",
    "Show the storage parameters for large objects",
    "Identify tables with materialized views",
    "List all columns with full-text search enabled",
    "Show the replication lag for the database",
    "Identify tables with data masking",
    "List all columns with check constraints",
    "Show the transaction isolation levels",
    "Identify tables with data compression",
    "List all columns with unique constraints",
    "Show the data type hierarchy",
    "Identify tables with user access logs",
    "List all columns with default functions",
    "Show the data model diagram",
    "Identify tables with high cardinality columns",
    "List all columns with foreign key dependencies",
    "Show the indexing frequency for columns",
    "Identify tables with redundant data",
    "List all columns with foreign key references",
    "Show the column-level security settings",
    "Identify tables with multi-column indexes",
    "List all columns with temporal constraints",
    "Show the data archiving strategies",
    "Identify tables with cross-references",
    "List all columns with reference integrity",
    "Show the synchronization settings",
    "Identify tables with data versioning",
    "List all columns with inheritance",
    "Show the backup encryption methods",
    "Identify tables with historical data",
    "List all columns with partitioning keys",
    "Show the data migration plans",
    "Identify tables with high availability configurations",
    "List all columns with transactional logs",
    "Show the data federation setups",
    "Identify tables with multi-tenancy support",
    "List all columns with indexed expressions",
    "Show the data governance policies",
    "Identify tables with real-time analytics",
    "List all columns with conditional defaults",
    "Show the load balancing settings",
    "Identify tables with event sourcing",
    "List all columns with advanced indexing",
    "Show the data caching mechanisms",
    "Identify tables with predictive analytics",
    "List all columns with dynamic constraints",
    "Show the data transformation rules",
    "Identify tables with machine learning integrations",
    "List all columns with user-defined validations",
    "Show the data quality metrics",
    "Identify tables with anomaly detection",
    "List all columns with business rules",
    "Show the data synchronization intervals",
    "Identify tables with temporal versioning",
    "List all columns with reference counts",
    "Show the data redundancy elimination techniques",
    "Identify tables with spatial relationships",
    "List all columns with multi-language support",
    "Show the data replication topologies",
    "Identify tables with time-series data",
    "List all columns with batch processing flags",
    "Show the data lineage tracking",
    "Identify tables with compliance constraints",
    "List all columns with audit fields",
    "Show the data anonymization processes",
    "Identify tables with access control lists",
    "List all columns with encryption keys",
    "Show the data partitioning schemes",
    "Identify tables with data federation",
    "List all columns with hashing functions",
    "Show the data indexing strategies",
    "Identify tables with load distribution",
    "List all columns with data transformation",
    "Show the data warehousing configurations",
    "Identify tables with reporting structures",
    "List all columns with normalization forms",
    "Show the data consolidation methods",
    "Identify tables with real-time data feeds",
    "List all columns with data masking rules",
    "Show the data sharding keys",
    "Identify tables with operational analytics",
    "List all columns with stream processing flags",
    "Show the data integration points",
    "Identify tables with transactional integrity",
    "List all columns with derived attributes",
    "Show the data synchronization protocols",
    "Identify tables with event-driven architectures",
    "List all columns with data validation rules",
    "Show the data transformation pipelines",
    "Identify tables with business intelligence integrations",
    "List all columns with lifecycle policies",
    "Show the data retention schedules",
    "Identify tables with data orchestration",
    "List all columns with event triggers",
    "Show the data synchronization mechanisms",
    "Identify tables with service-oriented architectures",
    "List all columns with data enrichment processes",
    "Show the data aggregation methods",
    "Identify tables with user activity logs",
    "List all columns with conditional constraints",
    "Show the data backup strategies",
    "Identify tables with distributed architectures",
    "List all columns with custom data types",
    "Show the data recovery procedures",
    "Identify tables with external integrations",
    "List all columns with user permissions",
    "Show the data validation frameworks",
    "Identify tables with data caching layers",
    "List all columns with access controls",
    "Show the data synchronization services",
    "Identify tables with metadata repositories",
    "List all columns with indexing options",
    "Show the data transformation rulesets",
    "Identify tables with data lifecycle management",
    "List all columns with data integrity checks",
    "Show the data federation services",
    "Identify tables with high-velocity data",
    "List all columns with data orchestration flags",
    "Show the data catalog configurations",
    "Identify tables with hybrid storage solutions",
    "List all columns with data consistency rules",
    "Show the data sharding strategies",
    "Identify tables with microservices integrations",
    "List all columns with versioning controls",
    "Show the data synchronization architectures",
    "Identify tables with data governance frameworks",
    "List all columns with replication settings",
    "Show the data masking configurations",
    "Identify tables with data anonymization protocols",
    "List all columns with access logging",
    "Show the data encryption standards",
    "Identify tables with schema evolution",
    "List all columns with indexing tiers",
    "Show the data partitioning keys",
    "Identify tables with data federation policies",
    "List all columns with data retention flags",
    "Show the data backup frequencies",
    "Identify tables with data mirroring",
    "List all columns with storage optimizations",
    "Show the data lifecycle stages",
    "Identify tables with archival processes",
    "List all columns with data replication policies",
    "Show the data integrity mechanisms",
    "Identify tables with data validation steps",
    "List all columns with transactional flags",
    "Show the data synchronization intervals",
    "Identify tables with data consistency models",
    "List all columns with replication factors",
    "Show the data federation methods",
    "Identify tables with multi-region support",
    "List all columns with data partition flags",
    "Show the data sharding configurations",
    "Identify tables with data redundancy policies",
    "List all columns with backup flags",
    "Show the data transformation standards",
    "Identify tables with data synchronization rules",
    "List all columns with data masking flags",
    "Show the data archiving configurations",
    "Identify tables with data lifecycle policies",
    "List all columns with encryption flags",
    "Show the data governance standards",
    "Identify tables with data quality controls",
    "List all columns with indexing flags",
    "Show the data retention policies",
    "Identify tables with data replication rules",
    "List all columns with data integrity flags",
    "Show the data synchronization settings",
    "Identify tables with data federation flags",
    "List all columns with backup settings",
    "Show the data transformation configurations",
    "Identify tables with data masking rules",
    "List all columns with archival flags",
    "Show the data lifecycle configurations",
    "Identify tables with data encryption rules",
    "List all columns with governance flags",
    "Qiojwfiamadoaijf",
    "asdlkfj0934@",
    "!!!!!dkamofao$#$$$dfoajfoakkfalmas",
    "Xkzmv9#@!klsd",
    "asdflkjweoiruqweoiru",
    "Qweruiopasdfghjklzxcvbnm",
    "lkajsdf09u23r09u23r",
    "plmoknijbuhv",
    "cxdvfrtgbnhy",
    "ujmikolp0987",
    "qazwsxedc321",
    "rfvtgbnhyujm",
    "ik,ol.POIUYT",
    "1234asdfghjkl",
    "erttyuiopZXCV",
    "bnm,./;'[]\\",
    "asdf!@#12345",
    "ZXCVbnm<>?:",
    "poiuytREWQ12",
    "asdfghJkl098",
    "zxcvbnM12345",
    "qwertYUIOP09",
    "123!@#abcDEF",
    "!@#$%^&*()_+",
    "lkjhgfdsaqwe",
    "rtyuio09876",
    "qwertyUIOP09",
    "QWERTY123456",
    "!@#ZXCVbnm<>",
    "asdf1234!@#$",
    "qwer5678%^&*",
    "zxcvbnm09876",
    "lkjhgfdsaQWE",
    "rfvtgbNhyujm",
    "asdf1234QWER",
    "ZXCVBNM0987",
    "qazwsxedcVFR",
    "tgbnhyUJMkl",
    "poiuyTREWQ12",
    "asdfGHJKL123",
    "zxcvbnM<>?:",
    "qwertyuiop[]\\",
    "asdfghjkl;'/",
    "q1w2e3r4t5y6",
    "u7i8o9p0-=",
    "!@#$%^&*()",
    "asdfQWER1234",
    "ZXCVBNM<>?:",
    "plmoknijbuhv",
    "ytrewq09876",
    "qazxswedcvfr",
    "tgbnhyujmkl,",
    "!@#QWEasd",
    "123!@#abcDEF",
    "ghjklPOIUYT",
    "zxc123456789",
    "asdfghjklQW",
    "ertyuiopZXCV",
    "asdf1234qwer",
    "!@#asdf$%^",
    "qazwsxedc123",
    "edcrfvtgb678",
    "1234567890-=+",
    "lkjhgfdsa!@#",
    "zxcvbnm0987",
    "qwertyuiop[]\\",
    "asdfghjkl;'/",
    "q1w2e3r4t5y6",
    "u7i8o9p0-=",
    "!@#$%^&*()dawewad",
    "asdfQWER1234",
    "ZXCVBNM<>?:",
    "plmoknijbuhv",
    "ytrewq09876",
    "qazxswedcvfr",
    "tgbnhyujmkl,",
    "!@#QWEasd",
    "123!@#abcDEF",
    "ghjklPOIUYT",
    "zxc123456789",
    "asdfghjklQW",
    "ertyuiopZXCV",
    "asdf1234qwer",
    "!@#asdf$%^",
    "qazwsxedc123",
    "edcrfvtgb678",
    "1234567890-=+",
    "lkjhgfdsa!@#",
    "zxcvbnm0987",
    "qwertyuiop[]\\",
    "asdfghjkl;'/",
    "q1w2e3r4t5y6",
    "u7i8o9p0-=",
    "!@#$%^&*()ijhdiosf",
    "asdfQWER1234",
    "ZXCVBNM<>?:",
    "plmoknijbuhv",
    "ytrewq09876",
    "qazxswedcvfr",
    "tgbnhyujmkl,",
    "!@#QWEasd",
    "123!@#abcDEF",
    "ghjklPOIUYT",
    "zxc123456789",
    "asdfghjklQW",
    "ertyuiopZXCV",
    "asdf1234qwer",
    "!@#asdf$%^",
    "qazwsxedc123",
    "edcrfvtgb678",
    "1234567890-=+",
    "lkjhgfdsa!@#",
    "zxcvbnm0987",
    "qwertyuiop[]\\",
    "asdfghjkl;'/",
    "q1w2e3r4t5y6",
    "u7i8o9p0-=",
    "!@#$%^&*(!!kjfaojdad",
    "asdfQWER1234",
    "ZXCVBNM<>?:",
    "plmoknijbuhv",
    "ytrewq09876",
    "qazxswedcvfr",
    "tgbnhyujmkl,",
    "!@#QWEasd",
    "123!@#abcDEF",
    "ghjklPOIUYT",
    "zxc123456789",
    "asdfghjklQW",
    "ertyuiopZXCV",
    "asdf1234qwer",
    "!@#asdf$%^",
    "qazwsxedc123",
    "edcrfvtgb678",
    "1234567890-=+",
    "Identify tables with federation settings",
    "List all columns with partitioning flags",
    "Show the data replication settings",
    "Identify tables with encryption rules",
    "List all columns with masking flags",
    "Show the data archiving configurations",
    "Identify tables with lifecycle settings",
    "List all columns with governance rules",
    "Show the data quality flags",
    "Identify tables with partitioning settings",
    "List all columns with replication flags",
    "Show the data consistency rules",
    "Identify tables with sharding settings",
    "List all columns with masking configurations",
    "Show the data governance flags",
    "Identify tables with validation settings",
    "List all columns with synchronization flags",
    "Show the data integrity rules",
    "Identify tables with backup settings",
    "List all columns with federation configurations",
    "Show the data partitioning flags",
    "Identify tables with replication settings",
    "List all columns with encryption rules",
    "Show the data masking flags",
    "Identify tables with lifecycle configurations",
    "List all columns with archiving flags",
    "Show the data quality rules",
    "Identify tables with consistency settings",
    "List all columns with replication configurations",
    "Show the data sharding rules",
    "Identify tables with masking settings",
    "List all columns with governance flags",
    "Show the data validation rules",
    "Identify tables with synchronization configurations",
    "List all columns with integrity flags",
    "Show the data backup rules",
    "Identify tables with federation flags",
    "List all columns with partitioning settings",
    "Show the data replication flags",
    "Identify tables with encryption configurations",
    "List all columns with masking rules",
    "Show the data archiving flags",
    "Identify tables with lifecycle rules",
    "List all columns with governance settings",
    "Show the data quality configurations",
    "Identify tables with partitioning flags",
    "List all columns with replication settings",
    "Show the data consistency rules",
    "Identify tables with sharding configurations",
    "List all columns with masking flags",
    "Show the data governance settings",
    "Identify tables with validation rules",
    "List all columns with synchronization configurations",
    "Show the data integrity flags",
    "Identify tables with backup configurations",
    "List all columns with federation settings",
    "Show the data partitioning rules",
    "Identify tables with replication flags",
    "List all columns with encryption settings",
    "Show the data masking configurations",
    "Identify tables with lifecycle flags",
    "List all columns with archiving settings",
    "Show the data quality flags",
    "Identify tables with consistency rules",
    "List all columns with replication configurations",
    "Show the data sharding settings",
    "Identify tables with masking rules",
    "List all columns with governance flags",
    "Show the data validation configurations",
    "Identify tables with synchronization rules",
    "List all columns with integrity settings",
    "Show the data backup flags",
    "Identify tables with federation configurations",
    "List all columns with partitioning flags",
    "Show the data replication rules",
    "Identify tables with encryption settings",
    "List all columns with masking configurations",
    "Show the data archiving flags",
    "Identify tables with lifecycle settings",
    "List all columns with governance rules",
    "Show the data quality settings",
    "Identify tables with partitioning flags",
    "List all columns with replication settings",
    "Show the data consistency configurations",
    "Identify tables with sharding rules",
    ]

    if num_questions > len(questions):
        raise ValueError(
            f"num_questions ({num_questions}) exceeds the total number of available questions ({len(questions)})."
        )
    
    selected_questions = questions[:num_questions]
    #selected_questions = random.sample(questions, num_questions)

    ans = []

    for question in selected_questions:
        output = text_to_sql(question, schema)
        ans.append(output)

    return ans
